resources:
  repositories:  
  - repository: hello-world
    type: github
    endpoint: github-connection
    name: shivangidevgan/hello-world
    ref: main

variables:
  - group: acr-variable-group
  - template: ci-variables.yaml
    parameters:
      projectName: "hello-world"
      chartName: "hello-world"
      #dockerRegistryServiceConnectionName: $(ACRConnection)
      #dockerfile: "$(Build.SourcesDirectory)/hello-world/src/Dockerfile.CI"
      imageTag: 0.1.$(Build.BuildId)
      isDotNetBased: true
      buildArgument: "--build-arg PAT=$(artifactsAccessToken)"
      
stages:
- stage: 'Build'
  displayName: 'Build'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: hello-world
      - template: ci-steps-template.yaml

- stage: Dev
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  jobs:
    - deployment: Deploy
      variables:
        - group: acr-variable-group
      displayName: Deploy
      pool:
        vmImage: ubuntu-18.04
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - template: cd-steps-template.yaml

- stage: Test
  displayName: 'Deploy to the Test environment'
  dependsOn: Dev
  jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: ubuntu-18.04
      environment: Test